cmake_minimum_required(VERSION 3.14)
project(ArbitraryInteger VERSION 3.0.0 LANGUAGES CXX)

add_library(arbitrary_integer src/ArbitraryInteger.cpp)
add_library(ArbitraryInteger::ArbitraryInteger ALIAS arbitrary_integer)
target_compile_features(arbitrary_integer PUBLIC cxx_std_11)
target_include_directories(arbitrary_integer PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
set_target_properties(arbitrary_integer PROPERTIES CXX_EXTENSIONS OFF)

set(arbitrary_integer_top_level OFF)
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
	set(arbitrary_integer_top_level ON)
endif()
option(ARBITRARY_INTEGER_BUILD_EXAMPLE "Build the example" ${arbitrary_integer_top_level})
if(ARBITRARY_INTEGER_BUILD_EXAMPLE)
	add_subdirectory(example)
endif()

if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
	include(CTest)
	if(BUILD_TESTING)
		add_subdirectory(test)
	endif()
endif()
